### ISSUE TITLE
iOS Crash with EXC_BAD_ACCESS when calling `Geolocator.getCurrentPosition`

### ISSUE THREAD

**Issue by johnspackman** [Baseflow/flutter-geolocator#1062]
## 🐛 Bug Report

My Flutter app is intermittently crashing during a call to `Geolocator.getCurrentPosition` - this is not an exception which can be caught with `try...catch`, the application simply terminates when running under the VSCode debugger.  On the few occasions when I have been able to make this happen while debugging with XCode, the error reported is EXC_BAD_ACCESS

It is intermittent, so I have lots of `print` statements and when the app terminates, the console output always stops at `*** moveToGpsLocation:: getting current GPS position`, see below:

```
      try {
        print("*** moveToGpsLocation:: getting current GPS position");
        position = await Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high, timeLimit: Duration(seconds: 20));
        print("*** moveToGpsLocation:: GPS position found: $position");
      } catch(error) {
        print("*** moveToGpsLocation:: GPS position not available: $error");
        if (userInteraction)
          await DialogManager.showAlert(Get.context!, "GPS is not available - please consider turning it on");
        position = await Geolocator.getLastKnownPosition();
      }
```

This is the debug console output:

```
[+3122 ms] flutter: *** _moveToGpsLocationWhenFree:: starting move
[        ] flutter: *** moveToGpsLocation:: start
[        ] flutter: *** checkUserPermission:: start
[ +182 ms] flutter: *** checkUserPermission:: available, previously granted permission
[        ] flutter: *** moveToGpsLocation:: getting current GPS position
[ +176 ms] Google Maps SDK for iOS version: 6.2.1.0
[ +777 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device (file:///Users/john/Library/Developer/CoreSimulator/Devices/48292EA7-75CB-4649-B947-FFA02A4D56E9/data/Containers/Data/Application/1B2DB1F1-609D-48F4-BAB6-96ABE9C9ACA6/tmp/KandulaAppz4Lzsc/KandulaApp/)
[ +252 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
```

Attached are screenshots from XCode when it caught the EXC_BAD_ACCESS exception; the error is in `glvmRasterOpDepthStencilTest` and in the previous stack element it appears that `UIApplicationMain` is trying to send the message "Application violated contract by causing UIApplicationMain() to return. This incident will be reported."

Google Maps is operating at the same time and it may be that Google Maps is also connecting to the Geolocator?  Am I supposed to control access to the Geolocator eg via exclusive lock etc?

### Expected behavior
Application does not crash

### Configuration

**Version:** 8.2.1

Version information from pubspec.lock

```
  geolocator:
    dependency: "direct main"
    description:
      name: geolocator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "8.2.1"
  geolocator_android:
    dependency: transitive
    description:
      name: geolocator_android
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.8"
  geolocator_apple:
    dependency: transitive
    description:
      name: geolocator_apple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  geolocator_platform_interface:
    dependency: transitive
    description:
      name: geolocator_platform_interface
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.5"
  geolocator_web:
    dependency: transitive
    description:
      name: geolocator_web
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5"
  geolocator_windows:
    dependency: transitive
    description:
      name: geolocator_windows
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1"
```

**Platform:** 
- [15.5] :iphone: iOS

flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.4 21F79 darwin-arm (Rosetta), locale en-GB)
    • Flutter version 3.0.0 at /Users/john/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (2 weeks ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/john/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.67.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (3 available)
    • iPhone 13 Pro Max (mobile) • 48292EA7-75CB-4649-B947-FFA02A4D56E9 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-5 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.4 21F79
      darwin-arm (Rosetta)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome
      101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
