### ISSUE TITLE
App crashing when Allow location permission [Android]

### ISSUE THREAD

**Issue by hashnetic** [Baseflow/flutter-geolocator#1230]
## 🐛 Bug Report

App is crashing when Allow location permission, location permission is requested like this:

LocationPermission permission = await Geolocator.requestPermission();

### Configuration

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ * ] :robot: Android

**Comment by NomiAdam** [comment]
Same here 😿. Seems like transitive dependency issue. In my case it was [camera](https://pub.dev/packages/camera) package bump which bumped `geolocator_android` to `4.1.7` from `4.1.4`

Quick fix was to force the older version
```yaml
# https://github.com/Baseflow/flutter-geolocator/issues/1230
dependency_overrides:
  geolocator_android: 4.1.4
```
