### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference

### ISSUE THREAD

**Issue by remoteportal** [Baseflow/flutter-geolocator#704]
## 🐛 Bug Report

In example, 'requestPermission' blows up:

```
  permission = await Geolocator.checkPermission();
  if (permission == LocationPermission.denied) {
    print('********** LocationPermission.denied');
    permission = await Geolocator.requestPermission();
    print('never see this line');
```

_One time_ with a different example  project it raised the permission dialog.  Every other time it just blows up.

It runs just fine if I manually add location permissions using Settings.

Run pane of Android Studio:

> I/flutter (20040): ********** LocationPermission.denied
> W/System.err(20040): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
> W/System.err(20040): 	at com.baseflow.geolocator.permission.PermissionUtils.hasPermissionInManifest(PermissionUtils.java:26)
> W/System.err(20040): 	at com.baseflow.geolocator.permission.PermissionManager.determineFineOrCoarse(PermissionManager.java:174)
> W/System.err(20040): 	at com.baseflow.geolocator.permission.PermissionManager.requestPermission(PermissionManager.java:76)
> W/System.err(20040): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onRequestPermission(MethodCallHandlerImpl.java:136)
> W/System.err(20040): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:59)
> W/System.err(20040): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> W/System.err(20040): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> W/System.err(20040): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
> W/System.err(20040): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> W/System.err(20040): 	at android.os.MessageQueue.next(MessageQueue.java:336)
> W/System.err(20040): 	at android.os.Looper.loop(Looper.java:181)
> W/System.err(20040): 	at android.app.ActivityThread.main(ActivityThread.java:7560)
> W/System.err(20040): 	at java.lang.reflect.Method.invoke(Native Method)
> W/System.err(20040): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
> W/System.err(20040): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> W/System.err(20040): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
> W/System.err(20040): 	at com.baseflow.geolocator.permission.PermissionUtils.hasPermissionInManifest(PermissionUtils.java:26)
> W/System.err(20040): 	at com.baseflow.geolocator.permission.PermissionManager.determineFineOrCoarse(PermissionManager.java:176)
> W/System.err(20040): 	at com.baseflow.geolocator.permission.PermissionManager.requestPermission(PermissionManager.java:76)
> W/System.err(20040): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onRequestPermission(MethodCallHandlerImpl.java:136)
> W/System.err(20040): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:59)
> W/System.err(20040): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> W/System.err(20040): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> W/System.err(20040): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
> W/System.err(20040): 	at android.os.MessageQueue.nativePollOnce(Native Method)
> W/System.err(20040): 	at android.os.MessageQueue.next(MessageQueue.java:336)
> W/System.err(20040): 	at android.os.Looper.loop(Looper.java:181)
> W/System.err(20040): 	at android.app.ActivityThread.main(ActivityThread.java:7560)
> W/System.err(20040): 	at java.lang.reflect.Method.invoke(Native Method)
> W/System.err(20040): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
> W/System.err(20040): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

### Expected behavior

Android location permission should raise.

### Reproduction steps

Run the example.

### Configuration

**Version:** geolocator: ^7.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

### Flutter

```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 2.0.3 at E:\src\flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\pete\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Mi 9T (mobile) • 844fb80a • android-arm64  • Android 10 (API 29)
    • Chrome (web)   • chrome   • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)     • edge     • web-javascript • Microsoft Edge 88.0.705.56

• No issues found!
```

### pubspec.xml

```
name: myApp
description: myApp

publish_to: 'none'
version: 1.0.95

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audio_service: ^0.17.0
  just_audio: ^0.7.2
  audioplayers: ^0.18.3
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  geolocator: ^7.0.1
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/btn-pause.png
    - assets/images/btn-play.png
    - assets/images/splash.png
```

### Device

Connected using USB-C to Windows PC.

Mi 9T Android phone
MIUI version 12.0.7 stable

Android version 10 QKQ1.190825.002
