### ISSUE TITLE
support for windows desktop

### ISSUE THREAD

**Issue by barbalex** [Baseflow/flutter-geolocator#840]
## 🚀 Feature Requests

Would be great if users with mobile windows devices could be included.

**Comment by barbalex** [comment]
Also dependent plugins could profit: https://github.com/tlserver/flutter_map_location_marker/issues/4#event-5360954434

**Comment by florian-lefebvre** [comment]
I need it too. Otherwise, great package!

**Comment by azchohfi** [comment]
I've started to implement this and will send a PR soon.

**Comment by mvanbeusekom** [comment]
I am happy to announce that @azchohfi PR has just been merged and the first version of the [geolocator_windows](https://pub.dev/packages/geolocator_windows) package has been published.

At the moment this package is not yet endorsed by the geolocator app-facing package but as a developer you can simply add a dependency on the geolocator_windows package to your pubspec.yaml file and use the geolocator as normal:

```yaml
dependencies:
  geolocator: ^8.0.4
  # Include dependency on the geolocator_windows package to add Windows support.
  geolocator_windows: ^0.1.0
```

Huge thank you to @azchohfi, amazing work.
